commands:
  # 바이트 데이터 명령 예제들 (16진수 형식)
  - receive: "AA BB CC DD EE FF"
    send: "AA 01 03 18 55"
    description: "예제 명령 1"

  - receive: "01 02 03 04"
    send: "FF FE FD FC"
    description: "예제 명령 2"

  - receive: "10 20 30"
    send: "A0 B0 C0"
    description: "예제 명령 3"

  - receive: "FF"
    send: "00"
    description: "단일 바이트 명령"

  - receive: "AA"
    send: "BB"
    description: "간단한 응답"

  # STX/ETX 프로토콜 예제
  - receive: "02 48 45 4C 4C 4F 03" # STX + "HELLO" + ETX
    send: "02 4F 4B 03" # STX + "OK" + ETX
    description: "HELLO 명령"

  - receive: "02 50 49 4E 47 03" # STX + "PING" + ETX
    send: "02 50 4F 4E 47 03" # STX + "PONG" + ETX
    description: "PING 명령"
