commands:
  # 바이트 데이터 명령 예제들 (16진수 형식)
  - receive: "AA BB CC DD EE FF"
    send: "AA 01 03 18 55"
    description: "예제 명령 1"

  - receive: "01 02 03 04"
    send: "FF FE FD FC"
    description: "예제 명령 2"

  - receive: "10 20 30"
    send: "A0 B0 C0"
    description: "예제 명령 3"

  - receive: "FF"
    send: "00"
    description: "단일 바이트 명령"

  - receive: "AA"
    send: "BB"
    description: "간단한 응답"

  # STX/ETX 프로토콜 예제
  - receive: "02 48 45 4C 4C 4F 03" # STX + "HELLO" + ETX
    send: "02 4F 4B 03" # STX + "OK" + ETX
    description: "HELLO 명령"

  - receive: "02 50 49 4E 47 03" # STX + "PING" + ETX
    send: "02 50 4F 4E 47 03" # STX + "PONG" + ETX
    description: "PING 명령"

  # 바이너리 프로토콜 예제
  - receive: "A5 5A 01 00" # 헤더 + 명령코드
    send: "A5 5A 81 00 00" # 헤더 + 응답코드 + 상태
    description: "상태 조회"

  - receive: "A5 5A 02 00"
    send: "A5 5A 82 01 00"
    description: "디바이스 정보"

  - receive: "A5 5A 03 00"
    send: "A5 5A 83 00 00"
    description: "리셋 명령"

  - receive: "AA 00 08 05 01 03 01 00 01 06 09 55"
    send: "AA 00 0E 03 01 05 01 01 01 0F 00 00 00 00 00 06 09 55"
    description: "테스트 #1"

  - receive: "AA 00 08 05 01 01 04 00 01 04 0C 55"
    send: "AA 00 14 04 01 05 01 01 01 00 00 00 00 00 00 00 00 00 00 00 00 06 09 55"
    description: "테스트 #2"
